from common import Element
import time
import random, re, string


class My_Product(Element.Element):
    def __init__(self, driver):
        self.driver = driver
        self.driver.implicitly_wait(50)
        print("-------开始产品使用知识测试-------")
        My_Product.get_name(self, "产品指南")
        print("点击产品指南")
        My_Product.get_name(self, '产品使用知识')
        My_Product.swipe_up(self, '1.如何使用空调更省电')
        My_Product.swipe_up(self, '1.如何使用空调更省电')
        My_Product.swipe_up(self, '2.空调运行的电压范围')
        My_Product.swipe_up(self, '2.空调运行的电压范围')
        My_Product.swipe_up(self, '3.空调室内机表面有水珠')
        My_Product.swipe_up(self, '3.空调室内机表面有水珠')
        My_Product.swipe_up(self, '4.空调有噪音，是什么原因')
        My_Product.swipe_up(self, '4.空调有噪音，是什么原因')
        My_Product.swipe_up(self, '5.空调无法开机或开机无反应')
        My_Product.swipe_up(self, '5.空调无法开机或开机无反应')
        My_Product.swipe_up(self, '6.空调开机后但不制冷或不制热或效果差')
        My_Product.swipe_up(self, '6.空调开机后但不制冷或不制热或效果差')
        My_Product.swipe_up(self, '7.空调开机一段时间后停机')
        My_Product.swipe_up(self, '7.空调开机一段时间后停机')
        My_Product.swipe_up(self, '8.空调关机后机器继续运转')
        My_Product.swipe_up(self, '8.空调关机后机器继续运转')
        My_Product.swipe_up(self, '9.制冷时室内机通风不畅，风速时快时慢')
        My_Product.swipe_up(self, '9.制冷时室内机通风不畅，风速时快时慢')
        My_Product.swipe_up(self, '10.空调制冷时排水管不出水正常吗')
        My_Product.swipe_up(self, '10.空调制冷时排水管不出水正常吗')
        My_Product.swipe_up(self, '11.空调制冷时出风口有“白雾”是否正常')
        My_Product.swipe_up(self, '11.空调制冷时出风口有“白雾”是否正常')
        My_Product.swipe_up(self, '12.空调降温慢，是不是空调制冷不正常')
        My_Product.swipe_up(self, '12.空调降温慢，是不是空调制冷不正常')
        My_Product.swipe_up(self, '13.空调多少时间需要加一次制冷剂')
        My_Product.swipe_up(self, '13.空调多少时间需要加一次制冷剂')
        My_Product.swipe_up(self, '14.制冷模式下关机后出风口还在吹风')
        My_Product.swipe_up(self, '14.制冷模式下关机后出风口还在吹风')
        My_Product.swipe_up(self, '15.电辅热有什么作用')
        My_Product.swipe_up(self, '15.电辅热有什么作用')
        My_Product.swipe_up(self, '16.制热时的耗电量比制冷时大吗')
        My_Product.swipe_up(self, '16.制热时的耗电量比制冷时大吗')
        My_Product.swipe_up(self, '17.制热中室外机有时会冒白烟，并有水流下')
        My_Product.swipe_up(self, '17.制热中室外机有时会冒白烟，并有水流下')
        My_Product.swipe_up(self, '18.制热时，室外机排水孔被冰堵塞')
        My_Product.swipe_up(self, '18.制热时，室外机排水孔被冰堵塞')
        My_Product.swipe_up(self, '19.制热中室内机运转一段时间后突然停止')
        My_Product.swipe_up(self, '19.制热中室内机运转一段时间后突然停止')
        My_Product.swipe_up(self, '20.空调制热时，化霜需要多长时间才能完成')
        My_Product.swipe_up(self, '20.空调制热时，化霜需要多长时间才能完成')
        My_Product.swipe_up(self, '21.制热时室外机不滴水是否正常')
        My_Product.swipe_up(self, '21.制热时室外机不滴水是否正常')
        My_Product.swipe_up(self, '22.带玻璃面板的柜机使用时玻璃面板会发热')
        My_Product.swipe_up(self, '22.带玻璃面板的柜机使用时玻璃面板会发热')
        My_Product.swipe_up(self, '23.如何实现一度到天明')
        My_Product.swipe_up(self, '23.如何实现一度到天明')
        My_Product.swipe_up(self, '24.变频空调有哪些优点')
        My_Product.swipe_up(self, '24.变频空调有哪些优点')
        My_Product.swipe_up(self, '25.变频空调为什么会省电一些')
        My_Product.swipe_up(self, '25.变频空调为什么会省电一些')
        My_Product.swipe_up(self, '26.变频空调在低频运行时外机风扇是否转动')
        My_Product.swipe_up(self, '26.变频空调在低频运行时外机风扇是否转动')
        My_Product.swipe_up(self, '27.冷暖空调，外机底部没接排水管，是否漏装')
        My_Product.swipe_up(self, '27.冷暖空调，外机底部没接排水管，是否漏装')
        My_Product.swipe_up(self, '28.变频无氟空调是不是不用加氟')
        My_Product.swipe_up(self, '28.变频无氟空调是不是不用加氟')
        My_Product.swipe_up(self, '29.如何设置空调定时开关机')
        My_Product.swipe_up(self, '29.如何设置空调定时开关机')
        My_Product.swipe_up(self, '30.空调移机对空调有影响吗')
        My_Product.swipe_up(self, '30.空调移机对空调有影响吗')
        My_Product.swipe_up(self, '31.空调室外机接头外滴水是否正常')
        My_Product.swipe_up(self, '31.空调室外机接头外滴水是否正常')
        My_Product.swipe_up(self, '32.空调“左右摆风”功能如何操作')
        My_Product.swipe_up(self, '32.空调“左右摆风”功能如何操作')
        My_Product.swipe_up(self, '33.新安装空调是否可以用旧空调的支架')
        My_Product.swipe_up(self, '33.新安装空调是否可以用旧空调的支架')
        My_Product.swipe_up(self, '34.挂机空调内机安装位置要求')
        My_Product.swipe_up(self, '34.挂机空调内机安装位置要求')
        My_Product.swipe_up(self, '35.空调室外机安装位置要求')
        My_Product.swipe_up(self, '35.空调室外机安装位置要求')
        My_Product.swipe_up(self, '36.奥克斯空调遥控器开不了机')
        My_Product.swipe_up(self, '36.奥克斯空调遥控器开不了机')
        My_Product.swipe_up(self, '37.冬季运行时外机表面会结霜是否正常？')
        My_Product.swipe_up(self, '37.冬季运行时外机表面会结霜是否正常？')
        My_Product.swipe_up(self, '38.制热时刚开机，内机没有热风吹出？')
        My_Product.swipe_up(self, '38.制热时刚开机，内机没有热风吹出？')
        time.sleep(1)
        My_Product.get_id(self, "com.broadlink.auxair:id/sLeftIconId")
        print("-------结束产品使用知识测试-------")