from common import Element
import random, re, string
import time


class My_personal(Element.Element):
    def __init__(self, driver):
        self.driver = driver
        print("-------开始个人资料测试-------")
        xing = '赵钱孙李周吴郑王冯陈褚卫蒋沈韩杨朱秦尤许何吕施张孔曹严华金魏陶姜'
        X = random.choice(xing)
        a = random.randint(1, 20)
        My_personal.get_name(self, '我的')
        print("我的页面")
        My_personal.get_name(self, '编辑个人资料')
        print('进入个人资料页面')
        My_personal.get_id(self, 'com.broadlink.auxair:id/iv_user_head')
        print('点击头像')
        My_personal.get_name(self, '取消')
        print('取消头像修改')
        My_personal.get_name(self, '昵称')
        print('点击昵称')
        My_personal.get_id(self, 'com.broadlink.auxair:id/iv_delete')
        print('清除昵称')
        My_personal.get_name(self, '完成')
        print('不输入昵称')
        My_personal.find_toast(self, text="请输入昵称")
        nicknameout = random.sample(string.ascii_letters + string.digits + X, 21)
        My_personal.get_Name(self, '请输入昵称').send_keys(nicknameout)
        print('输入20位以上昵称')
        My_personal.find_toast(self, text="昵称不能超过20位")
        My_personal.get_id(self, 'com.broadlink.auxair:id/iv_delete')
        print('清除昵称')
        nickname = random.sample(string.ascii_letters + string.digits + X, a)
        My_personal.get_Name(self, '请输入昵称').send_keys(nickname)
        print('输入20位以内昵称')
        self.driver.implicitly_wait(3)
        My_personal.get_name(self, '完成')
        My_personal.find_toast(self, text="修改成功")
        My_personal.get_name(self, '姓名')
        print('点击姓名')
        My_personal.get_id(self, 'com.broadlink.auxair:id/iv_delete')
        print('清除姓名')
        My_personal.get_name(self, '完成')
        print('不输入姓名')
        My_personal.find_toast(self, text="请输入姓名")
        fullnameout = random.sample(string.ascii_letters + string.digits + X, 21)
        My_personal.get_Name(self, '请输入姓名').send_keys(fullnameout)
        print('输入20位以上姓名')
        My_personal.find_toast(self, text="姓名不能超过20位")
        My_personal.get_id(self, 'com.broadlink.auxair:id/iv_delete')
        print('清除姓名')
        fullname = random.sample(string.ascii_letters + string.digits + X, a)
        My_personal.get_Name(self, '请输入姓名').send_keys(fullname)
        print('输入20位以内姓名')
        self.driver.implicitly_wait(3)
        My_personal.get_name(self, '完成')
        My_personal.find_toast(self, text="修改成功")
        My_personal.get_name(self, '性别')
        print('点击性别男')
        self.driver.implicitly_wait(3)
        My_personal.get_name(self, '男')
        My_personal.find_toast(self, text="修改成功")
        My_personal.get_name(self, '性别')
        print('点击性别女')
        self.driver.implicitly_wait(3)
        My_personal.get_name(self, '女')
        My_personal.find_toast(self, text="修改成功")
        self.driver.implicitly_wait(3)
        My_personal.get_name(self, '出生日期')
        print('点击出生日期')
        My_personal.get_name(self, '确定')
        My_personal.find_toast(self, text="修改成功")
        self.driver.implicitly_wait(3)
        My_personal.get_name(self, '所在地区')
        print('点击所在地区台湾省')
        My_personal.get_id(self, 'com.broadlink.auxair:id/textViewProvince')
        My_personal.swipe_up(self, "台湾省")
        My_personal.find_toast(self, text="修改成功")
        self.driver.implicitly_wait(3)
        My_personal.get_name(self, '所在地区')
        print('点击所在地区上海市')
        My_personal.swipe_down(self, "上海市")
        My_personal.get_name(self, '上海市辖区')
        My_personal.find_toast(self, text="修改成功")
