from common import Element
import time


class My_virtual(Element.Element):
    def __init__(self, driver):
        self.driver = driver
        print("-------开始虚拟体验测试-------")
        My_virtual.get_name(self, '我的')
        print("我的页面")
        My_virtual.get_name(self, '虚拟体验')
        print("点击虚拟体验")
        My_virtual.find_name(self, '虚拟体验')
        My_virtual.find_name(self, '当前26.0℃')
        My_virtual.get_id(self, "com.broadlink.auxair:id/addBtn")
        print("调高0.5℃")
        My_virtual.find_name(self, '.5')
        My_virtual.get_id(self, "com.broadlink.auxair:id/minutBtn")
        print("降低0.5℃")
        My_virtual.find_name(self, '27')
        My_virtual.swipe_up(self, "制热")
        print("制热")
        My_virtual.swipe_up(self, "制冷")
        print("制冷")
        My_virtual.swipe_up(self, "上下摆风")
        print("关闭上下摆风")
        My_virtual.swipe_up(self, "左右摆风")
        print("关闭左右摆风")
        My_virtual.swipe_up(self, "上下摆风")
        print("开启上下摆风")
        My_virtual.swipe_up(self, "左右摆风")
        print("开启左右摆风")
        My_virtual.swipe_up(self, "睡眠")
        print("打开睡眠")
        My_virtual.swipe_up(self, "健康")
        print("打开健康")
        My_virtual.swipe_up(self, "ECO")
        print("打开节能")
        My_virtual.swipe_up(self, "舒风")
        print("打开舒风")
        My_virtual.swipe_up(self, "童锁")
        print("打开童锁")
        My_virtual.swipe_up(self, "舒风")
        print("童锁下点击舒风")
        My_virtual.find_toast(self, text="空调处于锁定状态,解锁之后才能进行相应操作")
        My_virtual.swipe_up(self, "童锁")
        print("关闭童锁")
        My_virtual.swipe_up(self, "定时")
        print("点击定时")
        time.sleep(1)
        My_virtual.get_id(self, "com.broadlink.auxair:id/sLeftIconId")
        print("退出定时页面，返回虚拟体验主页面")
        My_virtual.swipe_up(self, "日用电曲线")
        print("点击日用电曲线")
        My_virtual.swipe_up(self, "月")
        My_virtual.swipe_up(self, "年")
        My_virtual.swipe_up(self, "日")
        My_virtual.get_id(self, "com.broadlink.auxair:id/iv_reduce")
        time.sleep(3)
        My_virtual.get_id(self, "com.broadlink.auxair:id/sLeftIconId")
        print("退出用电曲线页面，返回虚拟体验主页面")
        My_virtual.swipe_up(self, "用电限制")
        print("点击用电限制")
        My_virtual.get_id(self, "com.broadlink.auxair:id/power_limit_tv")
        My_virtual.get_id(self, "com.broadlink.auxair:id/seekbar_power_limit")
        My_virtual.swipe_up(self, "保存")
        My_virtual.find_toast(self, text="虚拟体验下不可使用该功能")
        time.sleep(3)
        My_virtual.get_id(self, "com.broadlink.auxair:id/power_limit_tv")
        My_virtual.swipe_up(self, "保存")
        My_virtual.find_toast(self, text="虚拟体验下不可使用该功能")
        time.sleep(3)
        My_virtual.get_id(self, "com.broadlink.auxair:id/sLeftIconId")
        print("退出用电曲线页面，返回虚拟体验主页面")
        My_virtual.swipe_up(self, "峰谷节电")
        print("点击峰谷节电")
        My_virtual.get_id(self, "com.broadlink.auxair:id/peak_open_tv")
        My_virtual.swipe_up(self, "保存")
        My_virtual.find_toast(self, text="虚拟体验下不可使用该功能")
        time.sleep(3)
        My_virtual.get_id(self, "com.broadlink.auxair:id/sLeftIconId")
        print("退出峰谷节电页面，返回虚拟体验主页面")
        My_virtual.swipe_up(self, "睡眠DIY")
        print("点击睡眠DIY")
        time.sleep(3)
        My_virtual.get_id(self, "com.broadlink.auxair:id/sLeftIconId")
        print("退出睡眠DIY页面，返回虚拟体验主页面")
        My_virtual.swipe_up(self, "智能用电")
        print("点击智能用电")
        My_virtual.get_id(self, "com.broadlink.auxair:id/tv_smart_power_open")
        My_virtual.get_id(self, "com.broadlink.auxair:id/iv_rg_2")
        My_virtual.swipe_up(self, "用电总量")
        My_virtual.swipe_up(self, "确定")
        My_virtual.swipe_up(self, "保存")
        My_virtual.find_toast(self, text="虚拟体验下不可使用该功能")
        time.sleep(3)
        My_virtual.get_id(self, "com.broadlink.auxair:id/sLeftIconId")
        print("退出智能用电页面，返回虚拟体验主页面")
        time.sleep(5)
        My_virtual.get_id(self, "com.broadlink.auxair:id/sLeftIconId")
        print("退出虚拟体验，返回我的页面")
        print("-------结束虚拟体验测试-------")
